### ISSUE TITLE
Add more args to Yake::new

### ISSUE THREAD

**Issue by bunny-therapist** [quesurifn/yake-rust#8]
Right now, there appears to be no way to change, e.g., the stop words.

**Comment by xamgore** [comment]
Have a branch for that, will PR a bit later.

**Comment by xamgore** [comment]
@bunny-therapist could you please test with my fork? Cargo.toml:

```toml
[patch.crates-io]
yake-rust = { git = "https://github.com/xamgore/yake-rust.git" }
```
